### ISSUE TITLE
‫[BUG] Installation fails on Python 3.12: fatal error: tensorview/pybind_utils.h: No such file or directory

### ISSUE THREAD

**Issue by danialfarsi** [traveller59/spconv#779]
### Description

I am trying to install `spconv-cu118` (and `cumm-cu118`) on **Python 3.12**, but the installation fails during the build process.

### Error Message
‫[1/40] [GCC][c++/pch]/usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch
FAILED: [code=1] /usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch
g++ -MMD -MT /usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch -MF /usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch.d -I "/usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include" -I "/usr/local/lib/python3.12/dist-packages/pybind11/include" -I "/usr/include/python3.12" -I "/usr/local/cuda/include" -I "/usr/local/lib/python3.12/dist-packages/include" -O3 -DTV_STATIC_VARIABLE_IMPLEMENTATION -std=c++14 -fPIC -x c++-header -DTV_ENABLE_HARDWARE_ACC -c /usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h -o /usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch
/usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:1:9: warning: #pragma once in main file
1 | #pragma once
| ^~~~
/usr/local/lib/python3.12/dist-packages/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:2:10: fatal error: tensorview/pybind_utils.h: No such file or directory
2 | #include <tensorview/pybind_utils.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

‫
### Environment

| Item | Detail |
|------|--------|
| OS | Google Colab (Linux) / Kaggle Notebooks |
| Python version | 3.12.13 |
| CUDA version | 11.8 (Colab) / 12.1 (Kaggle) |
| pip command | `pip install cumm-cu118 spconv-cu118` |
| spconv version | 2.3.8 |
| cumm version | 0.7.11 |
| GCC version | 11.4.0 |

### Steps to Reproduce

1. Open a new Google Colab or Kaggle notebook (Python 3.12 default)
2. Run: `!pip install cumm-cu118 spconv-cu118`
3. Observe the compilation error above

### Expected Behavior

Both packages should install successfully without compilation errors.

### Actual Behavior

The build process fails with `fatal error: tensorview/pybind_utils.h: No such file or directory`

### What I Have Tried (None Worked)

- Setting `SPCONV_DISABLE_JIT=1` environment variable
- Installing with `--no-cache-dir --force-reinstall`
- Installing `cumm` first separately with `--no-deps`
- Installing `spconv` from source (`python setup.py bdist_wheel`)
- Using different CUDA versions (cu118, cu120)

### Related Issues I Found

- Issue #37 in TRELLIS repo: "Seems like none of the versions of cumm would work in Python 3.12"
- Issue #766 in spconv repo: Similar `tensorview/pybind_utils.h` error (but on older Python version?)

### Questions

1. Does `cumm` / `spconv` officially support Python 3.12?
2. If not, is there a plan to add support?
3. Are there any workarounds (specific compilation flags, patching source, etc.)?

### Additional Context

This issue is blocking my research on **OpenCOOD** (cooperative perception framework) which depends on these libraries. Many researchers are facing the same problem because Google Colab and Kaggle now default to Python 3.12.

Any guidance would be greatly appreciated.

Thank you.

‫cc traveller59 and FindDefinition
